# Generated by Django 6.0.7 on 2026-08-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('minimum_gpa', models.FloatField(blank=True, null=True)),
                ('eligible_education_level', models.CharField(blank=True, max_length=200)),
                ('eligible_field', models.CharField(blank=True, max_length=200)),
                ('province_restriction', models.CharField(blank=True, max_length=200)),
                ('income_requirement_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gender_requirement', models.CharField(blank=True, max_length=50)),
                ('disability_requirement', models.BooleanField(default=False)),
                ('ethnicity_requirement', models.CharField(blank=True, max_length=100)),
                ('benefits', models.TextField()),
                ('required_documents', models.TextField()),
                ('deadline', models.DateField()),
                ('official_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
