# Generated by Django 6.0.7 on 2026-08-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='deadline_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='source_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='official_link',
            field=models.URLField(max_length=500),
        ),
    ]
