# Generated by Django 6.0.7 on 2026-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='marksheet',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has admin verified the user'),
        ),
    ]
