# Generated by Django 6.0.7 on 2026-08-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_marksheet_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='marksheet',
        ),
        migrations.AddField(
            model_name='user',
            name='marksheet',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
    ]
