# Generated by Django 6.0.7 on 2026-08-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_studentprofile_marksheet_user_marksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Has admin verified the user'),
        ),
    ]
